<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateStockmainTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('stock_mains', function (Blueprint $table) {
            $table->id();

            $table->string('name')->nullable();
            $table->string('family')->nullable();
            $table->string('cat')->nullable();
            $table->string('pays')->nullable();
            $table->string('staff')->nullable();
            $table->string('responsable')->nullable();
            $table->string('shop');
            $table->string('page_name')->nullable();
            $table->string('page_id');
            $table->string('zone')->nullable();
            $table->string('adresse')->nullable();
            $table->string('type')->nullable();
            $table->string('color')->nullable();
            $table->string('note')->nullable();
            $table->string('animal')->nullable();
            $table->string('saison')->nullable();
            $table->string('fuseaux')->nullable();
            $table->string('time')->nullable();
            $table->string('timing')->nullable();
            $table->integer('patecurry')->nullable();
            $table->integer('curry_roux')->nullable();
            $table->integer('curry_rice')->nullable();
            $table->integer('curry_udon')->nullable();
            $table->integer('croquette')->nullable();
            $table->integer('curry_poudre_blanc')->nullable();
            $table->integer('tomate')->nullable();
            $table->integer('onion')->nullable();
            $table->integer('carottes')->nullable();
            $table->integer('piment')->nullable();
            $table->integer('aubergine')->nullable();
            $table->integer('citroulle')->nullable();
            $table->integer('ail')->nullable();
            $table->integer('epinard')->nullable();
            $table->integer('gingimbre')->nullable();
            $table->integer('courgette')->nullable();
            $table->integer('pomme_de_terre')->nullable();
            $table->integer('poireaux')->nullable();
            $table->integer('persil')->nullable();
            $table->integer('coreandre')->nullable();
            $table->integer('laitue')->nullable();
            $table->integer('choux')->nullable();
            $table->integer('apple')->nullable();
            $table->integer('citron')->nullable();
            $table->integer('eau_s')->nullable();
            $table->integer('eau_l')->nullable();
            $table->integer('garci')->nullable();
            $table->integer('coca_normal')->nullable();
            $table->integer('coca_zero')->nullable();
            $table->integer('fanta1')->nullable();
            $table->integer('fanta2')->nullable();
            $table->integer('fruit1')->nullable();
            $table->integer('fruit2')->nullable();
            $table->integer('fruit3')->nullable();
            $table->integer('fruit4')->nullable();
            $table->integer('fruit5')->nullable();
            $table->integer('fruit6')->nullable();
            $table->integer('fruit7')->nullable();
            $table->integer('fruit8')->nullable();
            $table->integer('fruit9')->nullable();
            $table->integer('fruit10')->nullable();
            $table->integer('legume1')->nullable();
            $table->integer('legume2')->nullable();
            $table->integer('legume3')->nullable();
            $table->integer('legume4')->nullable();
            $table->integer('legume5')->nullable();
            $table->integer('legume6')->nullable();
            $table->integer('legume7')->nullable();
            $table->integer('legume8')->nullable();
            $table->integer('legume9')->nullable();
            $table->integer('legume10')->nullable();
            $table->integer('produit1')->nullable();
            $table->integer('produit2')->nullable();
            $table->integer('produit3')->nullable();
            $table->integer('produit4')->nullable();
            $table->integer('produit5')->nullable();
            $table->integer('produit6')->nullable();
            $table->integer('produit7')->nullable();
            $table->integer('produit8')->nullable();
            $table->integer('produit9')->nullable();
            $table->integer('produit10')->nullable();
            $table->integer('asia1')->nullable();
            $table->integer('asia2')->nullable();
            $table->integer('asia3')->nullable();
            $table->integer('asia4')->nullable();
            $table->integer('asia5')->nullable();
            $table->integer('asia6')->nullable();
            $table->integer('asia7')->nullable();
            $table->integer('asia8')->nullable();
            $table->integer('asia9')->nullable();
            $table->integer('asia10')->nullable();
            $table->integer('asia11')->nullable();
            $table->integer('asia12')->nullable();
            $table->integer('asia13')->nullable();
            $table->integer('asia14')->nullable();
            $table->integer('asia15')->nullable();
            $table->integer('sauce1')->nullable();
            $table->integer('sauce2')->nullable();
            $table->integer('sauce3')->nullable();
            $table->integer('sauce4')->nullable();
            $table->integer('sauce5')->nullable();
            $table->integer('sauce6')->nullable();
            $table->integer('sauce7')->nullable();
            $table->integer('sauce8')->nullable();
            $table->integer('sauce9')->nullable();
            $table->integer('sauce10')->nullable();
            $table->integer('sauce11')->nullable();
            $table->integer('sauce12')->nullable();
            $table->integer('sauce13')->nullable();
            $table->integer('sauce14')->nullable();
            $table->integer('sauce15')->nullable();
            $table->integer('drink1')->nullable();
            $table->integer('drink2')->nullable();
            $table->integer('drink3')->nullable();
            $table->integer('drink4')->nullable();
            $table->integer('drink5')->nullable();
            $table->integer('drink6')->nullable();
            $table->integer('drink7')->nullable();
            $table->integer('drink8')->nullable();
            $table->integer('drink9')->nullable();
            $table->integer('drink10')->nullable();
            $table->integer('desert1')->nullable();
            $table->integer('desert2')->nullable();
            $table->integer('desert3')->nullable();
            $table->integer('desert4')->nullable();
            $table->integer('desert5')->nullable();
            $table->integer('epicerie1')->nullable();
            $table->integer('epicerie2')->nullable();
            $table->integer('epicerie3')->nullable();
            $table->integer('epicerie4')->nullable();
            $table->integer('epicerie5')->nullable();
            $table->integer('epicerie6')->nullable();
            $table->integer('epicerie7')->nullable();
            $table->integer('epicerie8')->nullable();
            $table->integer('epicerie9')->nullable();
            $table->integer('epicerie10')->nullable();
            $table->integer('kitano1')->nullable();
            $table->integer('kitano2')->nullable();
            $table->integer('kitano3')->nullable();
            $table->integer('kitano4')->nullable();
            $table->integer('kitano5')->nullable();
            $table->integer('kitano6')->nullable();
            $table->integer('kitano7')->nullable();
            $table->integer('kitano8')->nullable();
            $table->integer('kitano9')->nullable();
            $table->integer('kitano10')->nullable();
            $table->integer('bn1')->nullable();
            $table->integer('bn2')->nullable();
            $table->integer('bn3')->nullable();
            $table->integer('bn4')->nullable();
            $table->integer('bn5')->nullable();
            $table->integer('bn6')->nullable();
            $table->integer('bn7')->nullable();
            $table->integer('bn8')->nullable();
            $table->integer('bn9')->nullable();
            $table->integer('bn10')->nullable();
            $table->integer('bn11')->nullable();
            $table->integer('bn12')->nullable();
            $table->integer('bn13')->nullable();
            $table->integer('bn14')->nullable();
            $table->integer('bn15')->nullable();
            $table->integer('bn16')->nullable();
            $table->integer('bn17')->nullable();
            $table->integer('bn18')->nullable();
            $table->integer('bn19')->nullable();
            $table->integer('bn20')->nullable();
            $table->integer('blue1')->nullable();
            $table->integer('blue2')->nullable();
            $table->integer('blue3')->nullable();
            $table->integer('blue4')->nullable();
            $table->integer('blue5')->nullable();
            $table->integer('blue6')->nullable();
            $table->integer('blue7')->nullable();
            $table->integer('blue8')->nullable();
            $table->integer('blue9')->nullable();
            $table->integer('blue10')->nullable();
            $table->integer('fm1')->nullable();
            $table->integer('fm2')->nullable();
            $table->integer('fm3')->nullable();
            $table->integer('fm4')->nullable();
            $table->integer('fm5')->nullable();
            $table->integer('fm6')->nullable();
            $table->integer('fm7')->nullable();
            $table->integer('fm8')->nullable();
            $table->integer('fm9')->nullable();
            $table->integer('fm10')->nullable();
            $table->integer('flg')->nullable();
            $table->integer('die')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('stock_mains');
    }
}
